### ISSUE TITLE
We need to be able to pass an environment to non rails app

### ISSUE THREAD

**Issue by brlanier** [amco/biran#40]
When using biran in non rails app, we need to be able to pass an environment.

**Comment by brlanier** [comment]
Also, I think there is a typo here - https://github.com/amco/biran/blob/master/lib/biran/configurinator.rb#L22

**Comment by brlanier** [comment]
Right now, it appears to be defaulting to using the default environment when not in rails with no way to set to something else from calling environment. 
Would like to see something maybe that accounted for several options so that even if we called the rake tasks using `RAILS_ENV=staging bundle exec rake config:generate` out of habit on a non rails app that it would still work. Like `env = ENV['BIRAN_ENV'] || ENV['RAILS_ENV']` or something like that

**Comment by javierg** [comment]
Well Biran is a rake task so IMO `RAKE_ENV` Makes more sense

**Comment by brlanier** [comment]
> Well Biran is a rake task so IMO RAKE_ENV Makes more sense

I was thinking about that this morning as well and using something like `RACK_ENV` or something else that might be standard. If `RAKE_ENV` is a thing then we can use that, if not, then we can consider using the `BIRAN_ENV` alternative to stick with naming convention of other environment variables for this gem. Just a thought.

**Comment by javierg** [comment]
Right Rack_env is a nothing not rake, sorry

**Comment by brlanier** [comment]
I think this can be closed
