### ISSUE TITLE
On travis the config generate task is not using correct environment variable

### ISSUE THREAD

**Issue by brlanier** [amco/biran#51]
When running config generate or any config tasks in travis, the task is not using the supplied `RAILS_ENV=development` on the command line.

This can be seen by including changes in the development block in the `config/app_config.yml` file and then checking the output in a generated file. You will not see the development values, only the default and possibly any values from test.

**Comment by brlanier** [comment]
Turns out travis sets the `RACK_ENV` as well as the `RAILS_ENV` to `test` on the builds. Based on the following line, the RACK_ENV is used to satisfy the condition before the RAILS_ENV is used
https://github.com/amco/biran/blob/v0.1.8/lib/biran/config_defaults.rb#L23
So the config tasks will use test values instead of the intended values passed in.

Solution is to either switch the order of the values in the default config, or call using a different environment variable first if we believe `RACK_ENV` should be used before `RAILS_ENV`.

**Comment by brlanier** [comment]
To be clear, I don't believe this to be an issue with travis, but an issue on which environment variable we try to use first.
Either we keep the current code and update the readme to indicate the preference and possibly update all of our apps when they update to new version of biran to use `RACK_ENV` or `BIRAN_APP_ENV` instead of `RAILS_ENV` in travis OR we change the order of precedence here such that we go Biran specific, rails, then rack which would be the more common use order. 
It is only in situations where we see `RACK_ENV` differ from `RAILS_ENV` would we see this issue. We create the difference in travis by wanting to run config:generate under a different env that what travis sets. I think in most cases only one would be set or they would be set the same.

**Comment by brlanier** [comment]
@javierg thoughts on this?

**Comment by javierg** [comment]
So in this case we will need to BIRAN_APP_ENV to something else, when running Travis? Will this still build the test block in settings?

**Comment by brlanier** [comment]
So yes, starting with biran v 0.1.8, using RAILS_ENV on travis will not give you what you expect. We would need to use the biran env variable, the rack env variable or my preference, change the order in the code to reflect the likely order of the variables being set:
`BIRAN_APP_ENV` is very specific since it exists only if set by the user. Not an artifact of other frameworks
`RAILS_ENV` is the more likely use case since that is the main target of the gem
`RACK_ENV` is the least likely use case and used in situations where you have a non rails rack based app or some other framework and you choose to set this variable over the biran specific one

I am not sure what you mean by building the test block. That is defined by the template. The issue is that the values pulled from app_config.yml would be pulled from the test block to build the settings.yml file instead of the expected development. In the specific case where I saw this today, there were values in the development block in app_config.yml that were not being used as expected. In most cases, this is a hidden bug that is not triggered, because in most cases, we have the default values be what would be used in development. But any app_config.yml file that had different values for development, would not see those changes when generating files WHEN using `RAILS_ENV` on travis, where `RACK_ENV` is set to something different... because `RACK_ENV` is preferred in logic.

**Comment by brlanier** [comment]
I believe, had I seen this when re-writing/adding that feature in biran, I would have changed the order then as it would be backwards compatible with expectations from our current installs.

**Comment by javierg** [comment]
so we will do:  ` ENV['BIRAN_APP_ENV'] || ENV['RAILS_ENV'] || ENV['RACK_ENV'] || configuration.app_env

**Comment by brlanier** [comment]
> so we will do: ` ENV['BIRAN_APP_ENV'] || ENV['RAILS_ENV'] || ENV['RACK_ENV'] || configuration.app_env

That would be my preferred change. I think that would keep the intended idea of the method. It was to help when non rails apps were installed to check to see if maybe RACK_ENV was set as a fall back. I have tried to think of a reason why would prefer rack env before rails env.

**Comment by javierg** [comment]
> I have tried to think of a reason why would prefer rack env before rails env.

I think is because we tried to do Ruby first, and Rails as an option.

**Comment by brlanier** [comment]
> I think is because we tried to do Ruby first, and Rails as an option.

I think it was the other way around where it worked in rails and we went back and tried to make it work in ruby only apps. The PR that added this change was related to that as originally, we were hooked to `RAILS_ENV`

**Comment by javierg** [comment]
Cool, are you  gonna do the PR for this?

**Comment by brlanier** [comment]
@javierg yes... I just wanted to make sure you were okay with the change I wanted to go with and that I wasn't missing something crazy.

**Comment by brlanier** [comment]
I think this can be closed
