### ISSUE TITLE
Update to psych 4 will cause issues with aliases in yaml files

### ISSUE THREAD

**Issue by brlanier** [amco/biran#88]
Biran uses safe_load which now disables loading of aliases by default in the safe_load method. 

We need to implement something like this or find another way in the `process_config_file` method

```
begin
  YAML.load(source, aliases: true, **options)
rescue ArgumentError
  YAML.load(source, **options)
end
```

https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias

**Comment by brlanier** [comment]
We may also want to consider having it symbolize the keys. We would need to see if this could avoid the deep_symbolize_keys call after the load
```
When the optional symbolize_names keyword argument is set to a true value, returns symbols for keys in [Hash](https://apidock.com/ruby/Hash) objects (default: strings).
```
https://apidock.com/ruby/v2_6_3/Psych/safe_load/class

As of right now, according to the code, we should be passing in to use aliases via the legacy_aliases option which is depreciated, but works.

**Comment by night91** [comment]
@brlanier When using rails 7.0 and ruby 3.1, this will causes errors for what you mentioned. Is there any workaround to make it work without overriding in the code this method in the current version 0.1.13.1?

For me a me `config_file_contents = YAML.safe_load(config_file_contents, aliases: true)` works, but I assume it will break older code using a lower psych version. Maybe a solution is to include a conditional based on psych version.

**Comment by brlanier** [comment]
> @brlanier When using rails 7.0 and ruby 3.1, this will causes errors for what you mentioned. Is there any workaround to make it work without overriding in the code this method in the current version 0.1.13.1?
> 
> For now: gem 'psych', '>= 3.3.2', '< 4.0.0' will work.

Right now, I don't know of a way around this. I have some time this week. I will see if I can add the  code to use the correct call based on version (or lack of argument).

**Comment by night91** [comment]
@brlanier for projects using amco/settingslogic fork this is also a issue here: https://github.com/amco/settingslogic/blob/master/lib/settingslogic.rb#L103

**Comment by brlanier** [comment]
> @brlanier for projects using amco/settingslogic fork this is also a issue here: https://github.com/amco/settingslogic/blob/master/lib/settingslogic.rb#L103

Cool, thanks... I will see about updating both of those. Can you let me know of a project I can use to test the changes against the newer psych 4.0 and ruby 3.1?  I would like to be able to make the changes and then test they work in my local against the current projects and a new project.

Thanks

**Comment by night91** [comment]
@brlanier you can use EE. Just need to remove `gem 'psych', '>= 3.3.2', '< 4.0.0'`and use the version 4. This will break in biran and settingslogic.

This after I merge my current PR (https://github.com/amco/ee/pull/2733).

**Comment by brlanier** [comment]
This was resolved and released already.
